### ISSUE TITLE
Analysis tab

### ISSUE THREAD

**Issue by masthantelecmi** [telecmi/TeleCMI-Support#15]
I just created vote ivr and in the 'app' tab i have choose 'map ivr' option -> vote. Also i have voted only for 2 times. But in the analysis tab it shows 5 cancelled calls. From my knowledge the vote ivr is no longer related to any agents, then why it is showing as 5 cancelled calls in the analysis tab ? since i have activated only vote in the 'map ivr' section in the 'app' tab. 

![analysistab](https://cloud.githubusercontent.com/assets/25261678/22193869/96ed2aa0-e164-11e6-8ed6-41ac9b0c1547.png)

**Comment by murugancmi** [comment]
Analysis not only for inbound call for IVR,Direct Queue not for vote IVR because no will call voted user but IVR and Direct Queue you may call again if you missed calls.  Agent chat shows agent missed calls and agent answer calls,Example if call IVR i never press any key just hangup it shows missed call in analysis chart not in agent chat because it never ring any agent hope you understand :)

**Comment by masthantelecmi** [comment]
analysis details tab

![analaysisdetails](https://cloud.githubusercontent.com/assets/25261678/22194214/dd08af58-e166-11e6-9f31-bdf578ae592b.png)

**Comment by murugancmi** [comment]
Better we change Agent Name into TO it may give clear idea

**Comment by murugancmi** [comment]
enhancement added
